// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for our ROS2 educational module
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index', // Main index page
    },
    {
      type: 'doc',
      id: 'glossary', // Glossary page
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 as the Robotic Nervous System',
          items: [
            'chapter-1/nervous-system',
            'chapter-1/role-in-physical-ai',
            'chapter-1/nodes-executors-dds',
            'chapter-1/control-architecture'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Nodes, Topics, and Services',
          items: [
            'chapter-2/communication-primitives',
            'chapter-2/data-flow',
            'chapter-2/control-patterns'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Python Agents with rclpy',
          items: [
            'chapter-3/python-control',
            'chapter-3/bridging-ai',
            'chapter-3/action-execution',
            'chapter-3/exercises'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Humanoid Modeling with URDF',
          items: [
            'chapter-4/urdf-structure',
            'chapter-4/links-joints-kinematics',
            'chapter-4/simulation-prep',
            'chapter-4/exercises'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'category',
          label: 'Chapter 5: Introduction to Digital Twins in Robotics',
          items: [
            'chapter-5/digital-twin-concepts',
            'chapter-5/digital-twin-benefits',
            'chapter-5/digital-twin-applications',
            'chapter-5/digital-twin-exercises'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 6: Gazebo-based Physics Simulation',
          items: [
            'chapter-6/gazebo-setup',
            'chapter-6/physics-modeling',
            'chapter-6/sensor-simulation',
            'chapter-6/gazebo-ros2-integration'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 7: Unity Integration and Humanoid Sensor Simulation',
          items: [
            'chapter-7/unity-setup',
            'chapter-7/visualization-techniques',
            'chapter-7/sensor-data-integration',
            'chapter-7/ros2-unity-bridge'
          ],
        },
      ],
    },
  ],
};

export default sidebars;
